BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Depenses` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PERS`	TEXT,
	`DATE`	INTEGER,
	`VAL`	INTEGER
);
INSERT INTO `Depenses` VALUES (1,'A',4,23);
INSERT INTO `Depenses` VALUES (2,'A',8,17);
INSERT INTO `Depenses` VALUES (3,'A',23,5);
INSERT INTO `Depenses` VALUES (4,'A',28,9);
INSERT INTO `Depenses` VALUES (5,'B',6,53);
INSERT INTO `Depenses` VALUES (6,'B',17,10);
INSERT INTO `Depenses` VALUES (7,'B',19,9);
INSERT INTO `Depenses` VALUES (8,'B',30,16);
INSERT INTO `Depenses` VALUES (9,'C',8,2);
INSERT INTO `Depenses` VALUES (10,'C',13,4);
INSERT INTO `Depenses` VALUES (11,'C',17,3);
INSERT INTO `Depenses` VALUES (12,'C',28,6);
INSERT INTO `Depenses` VALUES (13,'C',30,-20);
INSERT INTO `Depenses` VALUES (14,'D',15,4);
INSERT INTO `Depenses` VALUES (15,'D',21,9);
INSERT INTO `Depenses` VALUES (16,'D',30,-15);
INSERT INTO `Depenses` VALUES (17,'E',13,-4);
INSERT INTO `Depenses` VALUES (18,'E',14,3);
INSERT INTO `Depenses` VALUES (19,'E',15,1);
INSERT INTO `Depenses` VALUES (20,'E',30,-10);
INSERT INTO `Depenses` VALUES (21,'F',2,251);
INSERT INTO `Depenses` VALUES (22,'F',9,198);
INSERT INTO `Depenses` VALUES (23,'F',17,174);
INSERT INTO `Depenses` VALUES (24,'F',23,221);
INSERT INTO `Depenses` VALUES (25,'F',30,134);
COMMIT;
